version: '3.8'

services:
  nest2024-postgres:
    image: postgres:16.1
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-user}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-password}'
      POSTGRES_DB: '${POSTGRES_DB:-nest2024}'
    volumes:
      - ./nest2024-api-db:/var/lib/postgresql/nest2024

  june-2023-redis:
    image: redis:7.2.3
    ports:
      - '${REDIS_PORT:-6379}:6379'
    command: >
      --requirepass '${REDIS_PASSWORD:-redispass}'
    restart: unless-stopped

  june-2023-s3:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    restart: unless-stopped
    ports:
      - "9000:7000"
      - "7001:9001"
    volumes:
      - /nest2024-api-s3-data:/usr/src/app/s3
    environment:
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=password

volumes:
  june-2023-api-db:
  june-2023-api-s3: